import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import { motion } from "framer-motion"
import React from 'react';



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "web portafolio",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="bg-black " >
      <body className={inter.className}>
     {/*<motion.div
      variants={{
        hidden: { opacity: 0,y:75 }, 
        visible: { opacity: 1 ,y:0},
      }}
      > */}
        {children}
       {/* </motion.div>*/}
        </body>
    </html>
  );
}